# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Quantitative Psychology Active Learning Lab
author: Woojae Kim
email: woojae.kim@howard.edu
description: Quantitative Psychology Active Learning Lab where learning the mind and learning how to learn it occur actively
# baseurl: 
url: "https://wjaekim.github.io" 
logo: /images/lab-logo.svg

include:
  - .htaccess
  - _pages

sass:
  sass_dir: _sass

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false



# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links

# Jekyll sitemap
plugins:
  - jekyll-sitemap

# Jekyll SEO
plugins:
  - jekyll-seo-tag

